import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface": "var(--color-surface)",
        "on-primary": "var(--color-on-primary)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-surface": "var(--color-on-surface)",
        "surface-container": "var(--color-surface-container)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "secondary-container": "var(--color-secondary-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-dim": "var(--color-surface-dim)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "surface-tint": "var(--color-surface-tint)",
        "tertiary": "var(--color-tertiary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-secondary": "var(--color-on-secondary)",
        "on-error": "var(--color-on-error)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "error": "var(--color-error)",
        "error-container": "var(--color-error-container)",
        "on-background": "var(--color-on-background)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "primary": "var(--color-primary)",
        "outline-variant": "var(--color-outline-variant)",
        "on-error-container": "var(--color-on-error-container)",
        "outline": "var(--color-outline)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface-bright": "var(--color-surface-bright)",
        "secondary": "var(--color-secondary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "primary-container": "var(--color-primary-container)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "background": "var(--color-background)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-variant": "var(--color-surface-variant)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter-desktop": "1.5rem",
        "margin-desktop": "1.5rem",
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "space-lg": "1.25rem",
        "margin": "1rem"
      },
      "fontFamily": {
        "telemetry-lg": ["JetBrains Mono"],
        "headline-sm": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "headline-xl-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "telemetry-sm": ["JetBrains Mono"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "metric-display": ["JetBrains Mono"],
        "headline-xl": ["Inter"]
      },
      "fontSize": {
        "telemetry-lg": ["0.875rem", { "lineHeight": "1.25rem", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-sm": ["1rem", { "lineHeight": "1.5rem", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-caps": ["0.6875rem", { "lineHeight": "0.875rem", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "headline-xl-mobile": ["1.75rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["1.25rem", { "lineHeight": "1.75rem", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-lg": ["1rem", { "lineHeight": "1.5rem", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "telemetry-sm": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0em", "fontWeight": "500" }],
        "headline-lg": ["1.5rem", { "lineHeight": "2rem", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.005em", "fontWeight": "400" }],
        "body-md": ["0.875rem", { "lineHeight": "1.25rem", "letterSpacing": "0em", "fontWeight": "400" }],
        "metric-display": ["2rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "headline-xl": ["2.25rem", { "lineHeight": "2.75rem", "letterSpacing": "-0.025em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
};

export default config;
